import { Component, inject } from '@angular/core';
import { HeaderComponent } from '../../components/header/header.component';
import { BannerComponent } from '../../components/banner/banner.component';
import { MovieCarouselComponent } from '../../components/movie-carousel/movie-carousel.component';
import { Movie } from '../../types/Movie';
import { MovieService } from '../../services/movie.service';

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [HeaderComponent, BannerComponent, MovieCarouselComponent],
  templateUrl: './home.component.html',
  styleUrl: './home.component.css',
})
export class HomeComponent {
  // movies: Movie[] = [
  //   {
  //     adult: false,
  //     backdrop_path: '/5a4JdoFwll5DRtKMe7JLuGQ9yJm.jpg',
  //     genre_ids: [18, 878, 28],
  //     id: 695721,
  //     original_language: 'en',
  //     original_title: 'The Hunger Games: The Ballad of Songbirds & Snakes',
  //     overview:
  //       '64 years before he becomes the tyrannical president of Panem, Coriolanus Snow sees a chance for a change in fortunes when he mentors Lucy Gray Baird, the female tribute from District 12.',
  //     popularity: 2786.228,
  //     poster_path: '/mBaXZ95R2OxueZhvQbcEWy2DqyO.jpg',
  //     release_date: '2023-11-15',
  //     title: 'The Hunger Games: The Ballad of Songbirds & Snakes',
  //     video: false,
  //     vote_average: 7.2,
  //     vote_count: 964,
  //   },
  //   {
  //     adult: false,
  //     backdrop_path: '/bckxSN9ueOgm0gJpVJmPQrecWul.jpg',
  //     genre_ids: [28, 12, 14],
  //     id: 572802,
  //     original_language: 'en',
  //     original_title: 'Aquaman and the Lost Kingdom',
  //     overview:
  //       "Black Manta, still driven by the need to avenge his father's death and wielding the power of the mythic Black Trident, will stop at nothing to take Aquaman down once and for all. To defeat him, Aquaman must turn to his imprisoned brother Orm, the former King of Atlantis, to forge an unlikely alliance in order to save the world from irreversible destruction.",
  //     popularity: 1855.045,
  //     poster_path: '/8xV47NDrjdZDpkVcCFqkdHa3T0C.jpg',
  //     release_date: '2023-12-20',
  //     title: 'Aquaman and the Lost Kingdom',
  //     video: false,
  //     vote_average: 6.5,
  //     vote_count: 142,
  //   },
  //   {
  //     adult: false,
  //     backdrop_path: '/15Fe18IglCCP1jJoj5F529on0IA.jpg',
  //     genre_ids: [28, 35],
  //     id: 1029575,
  //     original_language: 'en',
  //     original_title: 'The Family Plan',
  //     overview:
  //       "Dan Morgan is many things: a devoted husband, a loving father, a celebrated car salesman. He's also a former assassin. And when his past catches up to his present, he's forced to take his unsuspecting family on a road trip unlike any other.",
  //     popularity: 1456.867,
  //     poster_path: '/jLLtx3nTRSLGPAKl4RoIv1FbEBr.jpg',
  //     release_date: '2023-12-14',
  //     title: 'The Family Plan',
  //     video: false,
  //     vote_average: 7.5,
  //     vote_count: 319,
  //   },
  //   {
  //     adult: false,
  //     backdrop_path: '/bmlkLCjrIWnnZzdAQ4uNPG9JFdj.jpg',
  //     genre_ids: [35, 10751, 14],
  //     id: 787699,
  //     original_language: 'en',
  //     original_title: 'Wonka',
  //     overview:
  //       'Willy Wonka – chock-full of ideas and determined to change the world one delectable bite at a time – is proof that the best things in life begin with a dream, and if you’re lucky enough to meet Willy Wonka, anything is possible.',
  //     popularity: 947.54,
  //     poster_path: '/qhb1qOilapbapxWQn9jtRCMwXJF.jpg',
  //     release_date: '2023-12-06',
  //     title: 'Wonka',
  //     video: false,
  //     vote_average: 7.2,
  //     vote_count: 504,
  //   },
  //   {
  //     adult: false,
  //     backdrop_path: '/9jPoyxjiEYPylUIMI3Ntixf8z3M.jpg',
  //     genre_ids: [16, 12, 35, 10751],
  //     id: 520758,
  //     original_language: 'en',
  //     original_title: 'Chicken Run: Dawn of the Nugget',
  //     overview:
  //       "A band of fearless chickens flock together to save poultry-kind from an unsettling new threat: a nearby farm that's cooking up something suspicious.",
  //     popularity: 770.14,
  //     poster_path: '/exNtEY8QUuQh9e23wSQjkPxKIU3.jpg',
  //     release_date: '2023-12-08',
  //     title: 'Chicken Run: Dawn of the Nugget',
  //     video: false,
  //     vote_average: 7.6,
  //     vote_count: 247,
  //   },
  //   {
  //     adult: false,
  //     backdrop_path: '/sLdlUypLzpQiJvO2dmqx5J7rigP.jpg',
  //     genre_ids: [27, 53, 9648],
  //     id: 1118595,
  //     original_language: 'en',
  //     original_title: 'The Jester',
  //     overview:
  //       'A malevolent being known as The Jester terrorizes the inhabitants of a small town on Halloween night, including two estranged sisters who must come together to find a way to defeat this evil entity.',
  //     popularity: 1084.223,
  //     poster_path: '/jsOaCojcuxktg8w1UQkoFfn1y1g.jpg',
  //     release_date: '2023-09-20',
  //     title: 'The Jester',
  //     video: false,
  //     vote_average: 5.9,
  //     vote_count: 73,
  //   },
  //   {
  //     adult: false,
  //     backdrop_path: '/ktHEdqmMWC1wdfPRMRCTZe2OISL.jpg',
  //     genre_ids: [27, 53, 9648],
  //     id: 1071215,
  //     original_language: 'en',
  //     original_title: 'Thanksgiving',
  //     overview:
  //       'After a Black Friday riot ends in tragedy, a mysterious Thanksgiving-inspired killer terrorizes Plymouth, Massachusetts - the birthplace of the holiday. Picking off residents one by one, what begins as random revenge killings are soon revealed to be part of a larger, sinister holiday plan.',
  //     popularity: 905.581,
  //     poster_path: '/f5f3TEVst1nHHyqgn7Z3tlwnBIH.jpg',
  //     release_date: '2023-11-16',
  //     title: 'Thanksgiving',
  //     video: false,
  //     vote_average: 6.6,
  //     vote_count: 247,
  //   },
  //   {
  //     adult: false,
  //     backdrop_path: '/gg4zZoTggZmpAQ32qIrP5dtnkEZ.jpg',
  //     genre_ids: [28, 80],
  //     id: 891699,
  //     original_language: 'en',
  //     original_title: 'Silent Night',
  //     overview:
  //       "A tormented father witnesses his young son die when caught in a gang's crossfire on Christmas Eve. While recovering from a wound that costs him his voice, he makes vengeance his life's mission and embarks on a punishing training regimen in order to avenge his son's death.",
  //     popularity: 949.959,
  //     poster_path: '/tlcuhdNMKNGEVpGqBZrAaOOf1A6.jpg',
  //     release_date: '2023-11-30',
  //     title: 'Silent Night',
  //     video: false,
  //     vote_average: 5.9,
  //     vote_count: 116,
  //   },
  //   {
  //     adult: false,
  //     backdrop_path: '/k1KrbaCMACQiq7EA0Yhw3bdzMv7.jpg',
  //     genre_ids: [16, 10751, 10402, 14, 35],
  //     id: 901362,
  //     original_language: 'en',
  //     original_title: 'Trolls Band Together',
  //     overview:
  //       "When Branch's brother, Floyd, is kidnapped for his musical talents by a pair of nefarious pop-star villains, Branch and Poppy embark on a harrowing and emotional journey to reunite the other brothers and rescue Floyd from a fate even worse than pop-culture obscurity.",
  //     popularity: 568.816,
  //     poster_path: '/bkpPTZUdq31UGDovmszsg2CchiI.jpg',
  //     release_date: '2023-10-12',
  //     title: 'Trolls Band Together',
  //     video: false,
  //     vote_average: 7.1,
  //     vote_count: 408,
  //   },
  //   {
  //     adult: false,
  //     backdrop_path: '/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg',
  //     genre_ids: [18, 36],
  //     id: 872585,
  //     original_language: 'en',
  //     original_title: 'Oppenheimer',
  //     overview:
  //       "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.",
  //     popularity: 635.446,
  //     poster_path: '/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
  //     release_date: '2023-07-19',
  //     title: 'Oppenheimer',
  //     video: false,
  //     vote_average: 8.1,
  //     vote_count: 5572,
  //   },
  //   {
  //     adult: false,
  //     backdrop_path: '/1X7vow16X7CnCoexXh4H4F2yDJv.jpg',
  //     genre_ids: [80, 18, 36],
  //     id: 466420,
  //     original_language: 'en',
  //     original_title: 'Killers of the Flower Moon',
  //     overview:
  //       'When oil is discovered in 1920s Oklahoma under Osage Nation land, the Osage people are murdered one by one—until the FBI steps in to unravel the mystery.',
  //     popularity: 596.636,
  //     poster_path: '/dB6Krk806zeqd0YNp2ngQ9zXteH.jpg',
  //     release_date: '2023-10-18',
  //     title: 'Killers of the Flower Moon',
  //     video: false,
  //     vote_average: 7.6,
  //     vote_count: 1565,
  //   },
  //   {
  //     adult: false,
  //     backdrop_path: '/zIYROrkHJPYB3VTiW1L9QVgaQO.jpg',
  //     genre_ids: [28, 35],
  //     id: 897087,
  //     original_language: 'en',
  //     original_title: 'Freelance',
  //     overview:
  //       'An ex-special forces operative takes a job to provide security for a journalist as she interviews a dictator, but a military coup breaks out in the middle of the interview, they are forced to escape into the jungle where they must survive.',
  //     popularity: 614.471,
  //     poster_path: '/7Bd4EUOqQDKZXA6Od5gkfzRNb0.jpg',
  //     release_date: '2023-01-05',
  //     title: 'Freelance',
  //     video: false,
  //     vote_average: 6.4,
  //     vote_count: 359,
  //   },
  //   {
  //     adult: false,
  //     backdrop_path: '/9PqD3wSIjntyJDBzMNuxuKHwpUD.jpg',
  //     genre_ids: [16, 35, 10751],
  //     id: 1075794,
  //     original_language: 'en',
  //     original_title: 'Leo',
  //     overview:
  //       'Jaded 74-year-old lizard Leo has been stuck in the same Florida classroom for decades with his terrarium-mate turtle. When he learns he only has one year left to live, he plans to escape to experience life on the outside but instead gets caught up in the problems of his anxious students — including an impossibly mean substitute teacher.',
  //     popularity: 523.352,
  //     poster_path: '/pD6sL4vntUOXHmuvJPPZAgvyfd9.jpg',
  //     release_date: '2023-11-17',
  //     title: 'Leo',
  //     video: false,
  //     vote_average: 7.6,
  //     vote_count: 647,
  //   },
  //   {
  //     adult: false,
  //     backdrop_path: '/t5zCBSB5xMDKcDqe91qahCOUYVV.jpg',
  //     genre_ids: [27, 9648],
  //     id: 507089,
  //     original_language: 'en',
  //     original_title: "Five Nights at Freddy's",
  //     overview:
  //       "Recently fired and desperate for work, a troubled young man named Mike agrees to take a position as a night security guard at an abandoned theme restaurant: Freddy Fazbear's Pizzeria. But he soon discovers that nothing at Freddy's is what it seems.",
  //     popularity: 512.581,
  //     poster_path: '/7BpNtNfxuocYEVREzVMO75hso1l.jpg',
  //     release_date: '2023-10-25',
  //     title: "Five Nights at Freddy's",
  //     video: false,
  //     vote_average: 7.8,
  //     vote_count: 2931,
  //   },
  //   {
  //     adult: false,
  //     backdrop_path: '/tLsc8SCFO0rMVgVyNm9XtfnyX84.jpg',
  //     genre_ids: [18, 9648, 53, 878],
  //     id: 726209,
  //     original_language: 'en',
  //     original_title: 'Leave the World Behind',
  //     overview:
  //       "A family's getaway to a luxurious rental home takes an ominous turn when a cyberattack knocks out their devices—and two strangers appear at their door.",
  //     popularity: 454.525,
  //     poster_path: '/29rhl1xopxA7JlGVVsf1UHfYPvN.jpg',
  //     release_date: '2023-11-22',
  //     title: 'Leave the World Behind',
  //     video: false,
  //     vote_average: 6.6,
  //     vote_count: 1056,
  //   },
  //   {
  //     adult: false,
  //     backdrop_path: '/4XM8DUTQb3lhLemJC51Jx4a2EuA.jpg',
  //     genre_ids: [28, 80, 53],
  //     id: 385687,
  //     original_language: 'en',
  //     original_title: 'Fast X',
  //     overview:
  //       "Over many missions and against impossible odds, Dom Toretto and his family have outsmarted, out-nerved and outdriven every foe in their path. Now, they confront the most lethal opponent they've ever faced: A terrifying threat emerging from the shadows of the past who's fueled by blood revenge, and who is determined to shatter this family and destroy everything—and everyone—that Dom loves, forever.",
  //     popularity: 498.514,
  //     poster_path: '/fiVW06jE7z9YnO4trhaMEdclSiC.jpg',
  //     release_date: '2023-05-17',
  //     title: 'Fast X',
  //     video: false,
  //     vote_average: 7.2,
  //     vote_count: 4520,
  //   },
  //   {
  //     adult: false,
  //     backdrop_path: '/gvNmnvu13TPAewP54hvCyuHwNwR.jpg',
  //     genre_ids: [28, 27, 878],
  //     id: 920081,
  //     original_language: 'en',
  //     original_title: 'Megaboa',
  //     overview:
  //       'On a trip to Colombia, a group of college students encounter a fifty-foot boa constrictor, hungry for blood.',
  //     popularity: 548.977,
  //     poster_path: '/sAnAMv3eyQiGI1z2k8NsvH0Y6r5.jpg',
  //     release_date: '2021-11-26',
  //     title: 'Megaboa',
  //     video: false,
  //     vote_average: 6.5,
  //     vote_count: 441,
  //   },
  //   {
  //     adult: false,
  //     backdrop_path: '/sRLC052ieEzkQs9dEtPMfFxYkej.jpg',
  //     genre_ids: [878, 28, 12],
  //     id: 848326,
  //     original_language: 'en',
  //     original_title: 'Rebel Moon - Part One: A Child of Fire',
  //     overview:
  //       'When a peaceful colony on the edge of the galaxy finds itself threatened by the armies of the tyrannical Regent Balisarius, they dispatch Kora, a young woman with a mysterious past, to seek out warriors from neighboring planets to help them take a stand.',
  //     popularity: 659.921,
  //     poster_path: '/ui4DrH1cKk2vkHshcUcGt2lKxCm.jpg',
  //     release_date: '2023-12-15',
  //     title: 'Rebel Moon - Part One: A Child of Fire',
  //     video: false,
  //     vote_average: 6.5,
  //     vote_count: 315,
  //   },
  //   {
  //     adult: false,
  //     backdrop_path: '/4uHyfIApZSRXSVEqSuk92PdN8Yx.jpg',
  //     genre_ids: [10751, 35, 14],
  //     id: 8871,
  //     original_language: 'en',
  //     original_title: 'How the Grinch Stole Christmas',
  //     overview:
  //       'The Grinch decides to rob Whoville of Christmas - but a dash of kindness from little Cindy Lou Who and her family may be enough to melt his heart...',
  //     popularity: 644.452,
  //     poster_path: '/52EpMoLTTbKAkM6rSrnNHV2mpLF.jpg',
  //     release_date: '2000-11-17',
  //     title: 'How the Grinch Stole Christmas',
  //     video: false,
  //     vote_average: 6.8,
  //     vote_count: 6927,
  //   },
  //   {
  //     adult: false,
  //     backdrop_path: '/5lWIYxYEqWi8j3ZloxXntw3ImBo.jpg',
  //     genre_ids: [16, 10751, 35, 14],
  //     id: 360920,
  //     original_language: 'en',
  //     original_title: 'The Grinch',
  //     overview:
  //       'The Grinch hatches a scheme to ruin Christmas when the residents of Whoville plan their annual holiday celebration.',
  //     popularity: 618.861,
  //     poster_path: '/1Bc9VNd9CIHIyJtPKFqSQzrXWru.jpg',
  //     release_date: '2018-11-08',
  //     title: 'The Grinch',
  //     video: false,
  //     vote_average: 6.8,
  //     vote_count: 3573,
  //   },
  // ];
  movies: Movie[] = [];
  movieService = inject(MovieService);

  ngOnInit(): void {
    this.movieService
      .getMovies()
      .subscribe((res) => (this.movies = res.result));
  }
}
